components:
  schema:
    Products:
      Response_products:
        type: object
        properties:
        id:
         type: string
          description: ID del producto
        title:
          type: string
          maxLength: 100
          description: El título del producto.
        description:
          type: string
          maxLength: 100
          description: La descripción del producto.
        price:
          type: number
          description: El precio del producto.
        category:
          type: string
          maxLength: 100
          description: La categoría del producto.
        code:
          type: string
          maxLength: 100
          uniqueItems: true
          description: El código del producto.
        stock:
          type: integer
          description: La cantidad de stock disponible del producto.
        thumbnails:
          type: array
          items:
            type: string
          description: Una lista de URLs de imágenes en miniatura del producto.
        status:
          type: boolean
          description: El estado del producto (activo/inactivo).
        example:
          id: 132331424-2213
          title: A23
          description: celular blanco
          price: 5000
          category: Cat1
          code: PT001
          stock: 1
          thumbnails: [./img1.jpg, ./img2.jpg]
          status: true
    